table hike_simulation
	lineageTag: 7068aefb-b964-5798-9209-dc438cfb6bad

	column employee_number
		dataType: int64
		formatString: 0
		lineageTag: 168c6f81-95e2-502f-907c-49f924524c69
		summarizeBy: none
		sourceColumn: employee_number

		annotation SummarizationSetBy = Automatic

	column hike_pct
		dataType: int64
		formatString: 0
		lineageTag: fd7f8e18-81b6-57c6-95d4-2ca049463035
		summarizeBy: none
		sourceColumn: hike_pct

		annotation SummarizationSetBy = Automatic

	column attrition_probability
		dataType: double
		formatString: 0.000
		lineageTag: c9021366-cc17-566a-99f7-8ef25ba1d022
		summarizeBy: none
		sourceColumn: attrition_probability

		annotation SummarizationSetBy = Automatic

	partition hike_simulation = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\alok\Desktop\hr\hike_simulation.csv"), [Delimiter = ",", Columns = 3, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"employee_number", Int64.Type}, {"hike_pct", Int64.Type}, {"attrition_probability", type number}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table
