table risk_scores
	lineageTag: eae5767d-cffa-5b95-b167-736ddffa03f7

	column employee_number
		dataType: int64
		formatString: 0
		lineageTag: 63f9f1e8-3861-5def-bc11-3e8ca2c91114
		summarizeBy: none
		sourceColumn: employee_number

		annotation SummarizationSetBy = Automatic

	column department
		dataType: string
		lineageTag: 5c05c3c7-1c4c-578a-a392-2a96a8a2eff8
		summarizeBy: none
		sourceColumn: department

		annotation SummarizationSetBy = Automatic

	column job_role
		dataType: string
		lineageTag: 24d0bae5-4068-513f-aed4-c87b8f2cf4c0
		summarizeBy: none
		sourceColumn: job_role

		annotation SummarizationSetBy = Automatic

	column over_time
		dataType: string
		lineageTag: 82928c62-f0d8-52d2-a336-b47d963fa467
		summarizeBy: none
		sourceColumn: over_time

		annotation SummarizationSetBy = Automatic

	column monthly_income
		dataType: int64
		formatString: 0
		lineageTag: daec2343-d989-5643-84e5-69b13fc1fb64
		summarizeBy: none
		sourceColumn: monthly_income

		annotation SummarizationSetBy = Automatic

	column years_at_company
		dataType: int64
		formatString: 0
		lineageTag: ed168be1-d97a-5dae-b4ff-ad084fca2d37
		summarizeBy: none
		sourceColumn: years_at_company

		annotation SummarizationSetBy = Automatic

	column attrition_probability
		dataType: double
		formatString: 0.000
		lineageTag: cb0f8be2-36d5-50e8-83de-f79a59520a5e
		summarizeBy: none
		sourceColumn: attrition_probability

		annotation SummarizationSetBy = Automatic

	column risk_band
		dataType: string
		lineageTag: dda26714-fd6c-528d-8510-cd75242f1748
		summarizeBy: none
		sourceColumn: risk_band

		annotation SummarizationSetBy = Automatic

	partition risk_scores = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\alok\Desktop\hr\employee_risk_scores.csv"), [Delimiter = ",", Columns = 8, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"employee_number", Int64.Type}, {"department", type text}, {"job_role", type text}, {"over_time", type text}, {"monthly_income", Int64.Type}, {"years_at_company", Int64.Type}, {"attrition_probability", type number}, {"risk_band", type text}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table
